<?php

/**
 * A unique identifier is defined to store the options in the database and reference them from the theme.
 */
function inkoption_framework_option_name() {
    // Change this to use your theme slug
    return 'inkthemes_options';
}

/**
 * Defines an array of options that will be used to generate the settings page and be saved in the database.
 * When creating the 'id' fields, make sure to use all lowercase and no spaces.
 *
 * If you are making your theme translatable, you should replace 'theme-textdomain'
 * with the actual text domain for your theme.  Read more:
 * http://codex.wordpress.org/Function_Reference/load_theme_textdomain
 */
function inkoption_framework_options() {
    $sec_on_off = array('on' => 'on', 'off' => 'off');
    $captcha_option = array("on" => "On", "off" => "Off");
    $home_page_blog_content = array("on" => "On", "off" => "Off");
    // Background Defaults
    $background_defaults = array('color' => '', 'image' => '', 'repeat' => 'repeat', 'position' => 'top center', 'attachment' => 'scroll');
    //Stylesheet Reader
    $alt_stylesheets = array("teal-green" => "teal-green", "green" => "green", "purple" => "purple", "pink" => "pink", "blue" => "blue", "yellow" => "yellow", "red" => "red", "black" => "black");
    $lan_stylesheets = array("Default" => "Default", "rtl" => "rtl");
    // Pull all the categories into an array
    $options_categories = array();
    $options_categories_obj = get_categories();
    foreach ($options_categories_obj as $category) {
        $options_categories[$category->cat_ID] = $category->cat_name;
    }

    // Populate OptionsFramework option in array for use in theme
    $contact_option = array("on" => "On", "off" => "Off");
    $captcha_option = array("on" => "On", "off" => "Off");
    // Pull all the pages into an array
    $options_pages = array();
    $options_pages_obj = get_pages('sort_column=post_parent,menu_order');
    $options_pages[''] = 'Select a page:';
    foreach ($options_pages_obj as $page) {
        $options_pages[$page->ID] = $page->post_title;
    }
    // If using image radio buttons, define a directory path
    $imagepath = get_template_directory_uri() . '/images/';

    $options = array(
        array("name" => __("General Settings", 'butterbelly'),
            "type" => "heading"),
        array("name" => __("Custom Logo", 'butterbelly'),
            "desc" => __("Upload a logo for your Website.", 'butterbelly'),
            "id" => "inkthemes_logo",
            "type" => "upload"),
        array("name" => __("Custom Favicon", 'butterbelly'),
            "desc" => __("Here you can upload a Favicon for your Website. Specified size is 16px x 16px.", 'butterbelly'),
            "id" => "inkthemes_favicon",
            "type" => "upload"),
        //Background Image
        array("name" => __("Background Image", 'butterbelly'),
            "desc" => __("Choose a suitable background image that will complement your website.", 'butterbelly'),
            "id" => "inkthemes_bodybg",
            "type" => "upload"),
        array("name" => __("Tracking Code", 'butterbelly'),
            "desc" => __("Paste your Google Analytics (or other) tracking code here.", 'butterbelly'),
            "id" => "inkthemes_analytics",
            "std" => "",
            "type" => "textarea"),
        /**
         * Tap to call settings
         */
        array("name" => __("Tap To Call", 'butterbelly'),
            "type" => "heading"),
        array("name" => __("Contact Number For Tap To Call Feature", 'butterbelly'),
            "desc" => __("Mention your contact number here through which users can interact to you directly. This feature is called tap to call and this will work when the user will access your website through mobile phones or iPhone.", 'butterbelly'),
            "id" => "inkthemes_contact_number",
            "std" => "",
            "type" => "text"),
        array("name" => __("Tap to call gradient top background color", 'butterbelly'),
            "desc" => "",
            "id" => "inkthemes_tapto_backtop",
            "std" => "",
            "type" => "color"),
        array("name" => __("Tap to call gradient bottom background color", 'butterbelly'),
            "desc" => "",
            "id" => "inkthemes_tapto_backbottom",
            "std" => "",
            "type" => "color"),
        array("name" => __("Box shadow color", 'butterbelly'),
            "desc" => "",
            "id" => "inkthemes_tapto_box_shadow",
            "std" => "",
            "type" => "color"),
        array("name" => __("Tap to call icon", 'butterbelly'),
            "desc" => sprintf(__("To change icon, go to <a href='%1s'>Font Awesome Icons Site</a> and select one icon and click the icon link. Once opened the page, copy the class property and paste on this field. For help, see this screennshot and copy only highlited text: <img src='%2s'/>", 'butterbelly'), esc_url('http://fortawesome.github.io/Font-Awesome/icons/'), esc_url(get_template_directory_uri() . "/assets/images/awesome-help.png")),
            "id" => "inkthemes_tapto_icon",
            "std" => "",
            "type" => "text"),
        array("name" => __("Text shadow color", 'butterbelly'),
            "desc" => "",
            "id" => "inkthemes_tapto_text_shadow",
            "std" => "",
            "type" => "color"),
        array("name" => __("Text color", 'butterbelly'),
            "desc" => "",
            "id" => "inkthemes_tapto_text_color",
            "std" => "",
            "type" => "color"),
        array("name" => __("Border color", 'butterbelly'),
            "desc" => "",
            "id" => "inkthemes_tapto_border_color",
            "std" => "",
            "type" => "color"),
        //Home Page Slider Setting
        array("name" => __("Slider Settings", 'butterbelly'),
            "type" => "heading"),
        //Slider Speed Setting	
        array("name" => __("Slider Speed", 'butterbelly'),
            "desc" => __("Set the speed of the slider in milliseconds. For e.g. if you want to set the speed of the slider for 8 seconds then enter 8000 in the field or if you want to set the slider speed for 2.5 seconds then enter 2500 in the field.", 'butterbelly'),
            "id" => "inkthemes_slide_speed",
            "std" => "8000",
            "type" => "text"),
        array("name" => __("First Slider Image", 'butterbelly'),
            "desc" => __("The optimal size of the image is 1600px wide x 825px height, but it can be varied as per your requirement.", 'butterbelly'),
            "id" => "inkthemes_slideimage1",
            "std" => "",
            "type" => "upload"),
        array("name" => __("First Slider Heading", 'butterbelly'),
            "desc" => __("Mention the heading for the First slider.", 'butterbelly'),
            "id" => "inkthemes_sliderheading1",
            "std" => "",
            "type" => "textarea"),
        array("name" => __("Link for First slider", 'butterbelly'),
            "desc" => __("Mention the URL for first image.", 'butterbelly'),
            "id" => "inkthemes_Sliderlink1",
            "std" => "",
            "type" => "text"),
        array("name" => __("First Slider Description", 'butterbelly'),
            "desc" => __("Here mention a short description for the First slider heading.", 'butterbelly'),
            "id" => "inkthemes_sliderdes1",
            "std" => "",
            "type" => "textarea"),
        array("name" => __("Link Text for First slider", 'butterbelly'),
            "desc" => __("Mention the link text for first slider.", 'butterbelly'),
            "id" => "inkthemes_slider_button1",
            "std" => "",
            "type" => "text"),
        //Second Slider
        array("name" => __("Second Slider", 'butterbelly'),
            "type" => "saperate",
            "class" => "saperator"),
        array("name" => __("Second Slider Image", 'butterbelly'),
            "desc" => __("The optimal size of the image is 1600px wide x 825px height, but it can be varied as per your requirement.", 'butterbelly'),
            "id" => "inkthemes_slideimage2",
            "std" => "",
            "type" => "upload"),
        array("name" => __("Second Slider Heading", 'butterbelly'),
            "desc" => __("Mention the heading for the Second slider.", 'butterbelly'),
            "id" => "inkthemes_sliderheading2",
            "std" => "",
            "type" => "textarea"),
        array("name" => __("Link for Second slider", 'butterbelly'),
            "desc" => __("Mention the URL for Second image.", 'butterbelly'),
            "id" => "inkthemes_Sliderlink2",
            "std" => "",
            "type" => "text"),
        array("name" => __("Second Slider Description", 'butterbelly'),
            "desc" => __("Here mention a short description for the Second slider heading.", 'butterbelly'),
            "id" => "inkthemes_sliderdes2",
            "std" => "",
            "type" => "textarea"),
        array("name" => __("Link Text for Second slider", 'butterbelly'),
            "desc" => __("Mention the link text for Second slider.", 'butterbelly'),
            "id" => "inkthemes_slider_button2",
            "std" => "",
            "type" => "text"),
        //Third Slider
        array("name" => __("Third Slider", 'butterbelly'),
            "type" => "saperate",
            "class" => "saperator"),
        array("name" => __("Third Slider Image", 'butterbelly'),
            "desc" => __("The optimal size of the image is 1600px wide x 825px height, but it can be varied as per your requirement.", 'butterbelly'),
            "id" => "inkthemes_slideimage3",
            "std" => "",
            "type" => "upload"),
        array("name" => __("Third Slider Heading", 'butterbelly'),
            "desc" => __("Mention the heading for the Third slider.", 'butterbelly'),
            "id" => "inkthemes_sliderheading3",
            "std" => "",
            "type" => "textarea"),
        array("name" => __("Link for Third slider", 'butterbelly'),
            "desc" => __("Mention the URL for Third image.", 'butterbelly'),
            "id" => "inkthemes_Sliderlink3",
            "std" => "",
            "type" => "text"),
        array("name" => __("Third Slider Description", 'butterbelly'),
            "desc" => __("Here mention a short description for the Third slider heading.", 'butterbelly'),
            "id" => "inkthemes_sliderdes3",
            "std" => "",
            "type" => "textarea"),
        array("name" => __("Link Text for Third slider", 'butterbelly'),
            "desc" => __("Mention the link text for Third slider.", 'butterbelly'),
            "id" => "inkthemes_slider_button3",
            "std" => "",
            "type" => "text"),
        //Fourth Slider
        array("name" => __("Fourth Slider", 'butterbelly'),
            "type" => "saperate",
            "class" => "saperator"),
        array("name" => __("Fourth Slider Image", 'butterbelly'),
            "desc" => __("The optimal size of the image is 1600px wide x 825px height, but it can be varied as per your requirement.", 'butterbelly'),
            "id" => "inkthemes_slideimage4",
            "std" => "",
            "type" => "upload"),
        array("name" => __("Fourth Slider Heading", 'butterbelly'),
            "desc" => __("Mention the heading for the Fourth slider.", 'butterbelly'),
            "id" => "inkthemes_sliderheading4",
            "std" => "",
            "type" => "textarea"),
        array("name" => __("Link for Fourth slider", 'butterbelly'),
            "desc" => __("Mention the URL for Fourth image.", 'butterbelly'),
            "id" => "inkthemes_Sliderlink4",
            "std" => "",
            "type" => "text"),
        array("name" => __("Fourth Slider Description", 'butterbelly'),
            "desc" => __("Here mention a short description for the Fourth slider heading.", 'butterbelly'),
            "id" => "inkthemes_sliderdes4",
            "std" => "",
            "type" => "textarea"),
        array("name" => __("Link Text for Fourth slider", 'butterbelly'),
            "desc" => __("Mention the link text for Fourth slider.", 'butterbelly'),
            "id" => "inkthemes_slider_button4",
            "std" => "",
            "type" => "text"),
        //Fifth Slider
        array("name" => __("Fifth Slider", 'butterbelly'),
            "type" => "saperate",
            "class" => "saperator"),
        array("name" => __("Fifth Slider Image", 'butterbelly'),
            "desc" => __("The optimal size of the image is 1600px wide x 825px height, but it can be varied as per your requirement.", 'butterbelly'),
            "id" => "inkthemes_slideimage5",
            "std" => "",
            "type" => "upload"),
        array("name" => __("Fifth Slider Heading", 'butterbelly'),
            "desc" => __("Mention the heading for the Fifth slider.", 'butterbelly'),
            "id" => "inkthemes_sliderheading5",
            "std" => "",
            "type" => "textarea"),
        array("name" => __("Link for Fifth slider", 'butterbelly'),
            "desc" => __("Mention the URL for Fifth image.", 'butterbelly'),
            "id" => "inkthemes_Sliderlink5",
            "std" => "",
            "type" => "text"),
        array("name" => __("Fifth Slider Description", 'butterbelly'),
            "desc" => __("Here mention a short description for the Fifth slider heading.", 'butterbelly'),
            "id" => "inkthemes_sliderdes5",
            "std" => "",
            "type" => "textarea"),
        array("name" => __("Link Text for Fifth slider", 'butterbelly'),
            "desc" => __("Mention the link text for Fifth slider.", 'butterbelly'),
            "id" => "inkthemes_slider_button5",
            "std" => "",
            "type" => "text"),
        //Sixth Slider
        array("name" => __("Sixth Slider", 'butterbelly'),
            "type" => "saperate",
            "class" => "saperator"),
        array("name" => __("Sixth Slider Image", 'butterbelly'),
            "desc" => __("The optimal size of the image is 1600px wide x 825px height, but it can be varied as per your requirement.", 'butterbelly'),
            "id" => "inkthemes_slideimage6",
            "std" => "",
            "type" => "upload"),
        array("name" => __("Sixth Slider Heading", 'butterbelly'),
            "desc" => __("Mention the heading for the Sixth slider.", 'butterbelly'),
            "id" => "inkthemes_sliderheading6",
            "std" => "",
            "type" => "textarea"),
        array("name" => __("Link for Sixth slider", 'butterbelly'),
            "desc" => __("Mention the URL for Sixth image.", 'butterbelly'),
            "id" => "inkthemes_Sliderlink6",
            "std" => "",
            "type" => "text"),
        array("name" => __("Sixth Slider Description", 'butterbelly'),
            "desc" => __("Here mention a short description for the Sixth slider heading.", 'butterbelly'),
            "id" => "inkthemes_sliderdes6",
            "std" => "",
            "type" => "textarea"),
        array("name" => __("Link Text for Sixth slider", 'butterbelly'),
            "desc" => __("Mention the link text for Sixth slider.", 'butterbelly'),
            "id" => "inkthemes_slider_button6",
            "std" => "",
            "type" => "text"),
        //Homepage Feature Area
        array("name" => __("Homepage Feature Area", 'butterbelly'),
            "type" => "heading"),
        array("name" => __("Feature Section On/Off", 'butterbelly'),
            "desc" => __("Choose option to show/hide feature area", 'butterbelly'),
            "id" => "inkthemes_feature_section",
            "std" => "on",
            "type" => "radio",
            "options" => $sec_on_off),
        array("name" => __("First Feature Image", 'butterbelly'),
            "desc" => __("Choose image for your first Feature area. Optimal size 354px x 172px", 'butterbelly'),
            "id" => "inkthemes_fimg1",
            "std" => "",
            "type" => "upload"),
        array("name" => __("First Feature Circle Image", 'butterbelly'),
            "desc" => __("Choose image for your first Feature Circle area. Optimal size 143px x 143px", 'butterbelly'),
            "id" => "inkthemes_circle_img1",
            "std" => "",
            "type" => "upload"),
        array("name" => __("First Feature Heading", 'butterbelly'),
            "desc" => __("Enter your text for first feature heading.", 'butterbelly'),
            "id" => "inkthemes_headline1",
            "std" => "",
            "type" => "textarea"),
        array("name" => __("First Feature Description", 'butterbelly'),
            "desc" => __("Enter your text for first feature description.", 'butterbelly'),
            "id" => "inkthemes_firstdesc",
            "std" => "",
            "type" => "textarea"),
        array("name" => __("First feature Link", 'butterbelly'),
            "desc" => __("Enter your text for First feature Link.", 'butterbelly'),
            "id" => "inkthemes_feature_link1",
            "std" => "",
            "type" => "text"),
        array("name" => __("Second Feature Starts From Here.", 'butterbelly'),
            "type" => "saperate",
            "class" => "saperator"),
        //Second Feature Separetor
        array("name" => __("Second Feature Image", 'butterbelly'),
            "desc" => __("Choose image for your second Feature area. Optimal size 354px x 172px", 'butterbelly'),
            "id" => "inkthemes_fimg2",
            "std" => "",
            "type" => "upload"),
        array("name" => __("Second Feature Circle Image", 'butterbelly'),
            "desc" => __("Choose image for your Second Feature Circle area. Optimal size 143px x 143px", 'butterbelly'),
            "id" => "inkthemes_circle_img2",
            "std" => "",
            "type" => "upload"),
        array("name" => __("Second Feature Heading", 'butterbelly'),
            "desc" => __("Enter your heading for second Feature area", 'butterbelly'),
            "id" => "inkthemes_headline2",
            "std" => "",
            "type" => "textarea"),
        array("name" => __("Second feature Description", 'butterbelly'),
            "desc" => __("Enter your text for second feature description.", 'butterbelly'),
            "id" => "inkthemes_seconddesc",
            "std" => "",
            "type" => "textarea"),
        array("name" => __("Second feature Link", 'butterbelly'),
            "desc" => __("Enter your text for Second feature Link.", 'butterbelly'),
            "id" => "inkthemes_feature_link2",
            "std" => "",
            "type" => "text"),
        array("name" => __("Third Feature Starts From Here.", 'butterbelly'),
            "type" => "saperate",
            "class" => "saperator"),
        //Third Feature Separetor
        array("name" => __("Third Feature Image", 'butterbelly'),
            "desc" => __("Choose image for your thirdthirdthird Feature. Optimal size 354px x 172px", 'butterbelly'),
            "id" => "inkthemes_fimg3",
            "std" => "",
            "type" => "upload"),
        array("name" => __("Third Feature Circle Image", 'butterbelly'),
            "desc" => __("Choose image for your Third Feature Circle area. Optimal size 143px x 143px", 'butterbelly'),
            "id" => "inkthemes_circle_img3",
            "std" => "",
            "type" => "upload"),
        array("name" => __("Third Feature Heading", 'butterbelly'),
            "desc" => __("Enter your heading for third Feature area", 'butterbelly'),
            "id" => "inkthemes_headline3",
            "std" => "",
            "type" => "textarea"),
        array("name" => __("Third Feature Description", 'butterbelly'),
            "desc" => __("Enter your text for Third Feature description.", 'butterbelly'),
            "id" => "inkthemes_thirddesc",
            "std" => "",
            "type" => "textarea"),
        array("name" => __("Third feature Link", 'butterbelly'),
            "desc" => __("Enter your text for Third feature Link.", 'butterbelly'),
            "id" => "inkthemes_feature_link3",
            "std" => "",
            "type" => "text"),
        //Home Page Bottom Feature Area		
        array("name" => __("Home Page Bottom Feature", 'butterbelly'),
            "type" => "heading"),
        array("name" => __("Home Page Services Feature Heading", 'butterbelly'),
            "desc" => __("Enter your heading for Home Page Services Feature", 'butterbelly'),
            "id" => "inkthemes_services_head",
            "std" => "",
            "type" => "textarea"),
        array("name" => __("Home Page Services Feature Description", 'butterbelly'),
            "desc" => __("Enter your text for Home Page Services Feature description.", 'butterbelly'),
            "id" => "inkthemes_services_desc",
            "std" => "",
            "type" => "textarea"),
        array("name" => __("Home Page Tab Feature Start From Here", 'butterbelly'),
            "type" => "saperate",
            "class" => "saperator"),
        array("name" => __("First Tab Heading", 'butterbelly'),
            "desc" => __("Enter your text for First Tab Heading", 'butterbelly'),
            "id" => "inkthemes_tab_head1",
            "std" => "",
            "type" => "textarea"),
        array("name" => __("First Tab Description", 'butterbelly'),
            "desc" => __("Enter your text for First Tab Description", 'butterbelly'),
            "id" => "inkthemes_tab_desc1",
            "std" => "",
            "type" => "textarea"),
        array("name" => __("Second Tab Heading", 'butterbelly'),
            "desc" => __("Enter your text for Second Tab Heading", 'butterbelly'),
            "id" => "inkthemes_tab_head2",
            "std" => "",
            "type" => "textarea"),
        array("name" => __("Second Tab Description", 'butterbelly'),
            "desc" => __("Enter your text for Second Tab Description", 'butterbelly'),
            "id" => "inkthemes_tab_desc2",
            "std" => "",
            "type" => "textarea"),
        array("name" => __("Third Tab Heading", 'butterbelly'),
            "desc" => __("Enter your text for Third Tab Heading", 'butterbelly'),
            "id" => "inkthemes_tab_head3",
            "std" => "",
            "type" => "textarea"),
        array("name" => __("Third Tab Description", 'butterbelly'),
            "desc" => __("Enter your text for Third Tab Description", 'butterbelly'),
            "id" => "inkthemes_tab_desc3",
            "std" => "",
            "type" => "textarea"),
        array("name" => __("Fourth Tab Heading", 'butterbelly'),
            "desc" => __("Enter your text for Fourth Tab Heading", 'butterbelly'),
            "id" => "inkthemes_tab_head4",
            "std" => "",
            "type" => "textarea"),
        array("name" => __("Fourth Tab Description", 'butterbelly'),
            "desc" => __("Enter your text for Fourth Tab Description", 'butterbelly'),
            "id" => "inkthemes_tab_desc4",
            "std" => "",
            "type" => "textarea"),
        array("name" => __("Home Page Right Widget Area Start From Here", 'butterbelly'),
            "type" => "saperate",
            "class" => "saperator"),
        array("name" => __("Home Page Right Widget Area", 'butterbelly'),
            "desc" => __("Enter your text Or Iframe Code For Home Page Right Widget Area. If You Can Activate Home Page Sidebar From Widget Section Then It Will Disappear.", 'butterbelly'),
            "id" => "inkthemes_right_widget",
            "std" => "",
            "type" => "textarea"),
        array("name" => __("Home Page Blog Feature Start From Here", 'butterbelly'),
            "type" => "saperate",
            "class" => "saperator"),
        array("name" => __("Home Page Blog Heading Text", 'butterbelly'),
            "desc" => __("Here you can mention a suitable blog text that will display the recent blog posts with images.", 'butterbelly'),
            "id" => "inkthemes_blog_heading",
            "std" => "",
            "type" => "textarea"),
        array("name" => __("Home Page Blog Description Text", 'butterbelly'),
            "desc" => __("Here you can mention a suitable blog text that will display the recent blog posts with images.", 'butterbelly'),
            "id" => "inkthemes_blog_desc",
            "std" => "",
            "type" => "textarea"),
        array("name" => __("Number Of Post", 'butterbelly'),
            "desc" => __("Here you can mention the number of blog post that will display on home page.", 'butterbelly'),
            "id" => "inkthemes_blog_post",
            "std" => "3",
            "type" => "text"),
        /**
         * Home Page Product Setting
         */
        array("name" => __("Home Product Page Settings", "butterbelly"),
            "type" => "heading"),
        array("name" => __("Homepage Product Section On/Off", "butterbelly"),
            "desc" => __("Show/Hide hompage product section", "butterbelly"),
            "id" => "inkthemes_product_sec_on_off",
            "std" => "off",
            "type" => "radio",
            "options" => $sec_on_off),
        array("name" => __("Product Page Heading", "butterbelly"),
            "desc" => __("Enter heading text for homepage product section", "butterbelly"),
            "id" => "inkthemes_prod_sec_head",
            "std" => "",
            "type" => "text"),
        array("name" => __("Number of Products Page Heading", "butterbelly"),
            "desc" => __("Enter the number of products to show in homepage product section", "butterbelly"),
            "id" => "inkthemes_prod_no",
            "std" => "8",
            "type" => "text"),
//****=============================================================================****//
//****-----------This code is used for creating color styleshteet options----------****//							
//****=============================================================================****//
        array("name" => __("Contact Page Settings", 'butterbelly'),
            "type" => "heading"),
        //Second Heading
        array("name" => __("Contact Page Map", 'butterbelly'),
            "desc" => __("Go to https://maps.google.com/ and generate the map for your location. Just copy only the iframe code i.e. code within &lt;iframe&gt; and &lt;/iframe&gt; and paste it here. This will show the map location of your business on the Website.", 'butterbelly'),
            "id" => "inkthemes_contact_map",
            "std" => "",
            "type" => "textarea"),
        array("name" => __("Recaptcha Public Key", 'butterbelly'),
            "desc" => __("Go to http://www.google.com/recaptcha/admin/create to Create your Private key", 'butterbelly'),
            "id" => "recaptcha_public",
            "std" => "",
            "type" => "text"),
        array("name" => __("Recaptcha Private Key", 'butterbelly'),
            "desc" => __("Go to http://www.google.com/recaptcha/admin/create to Create your Private key", 'butterbelly'),
            "id" => "recaptcha_private",
            "std" => "",
            "type" => "text"),
        array("name" => __("Recaptcha On/Off", 'butterbelly'),
            "desc" => __("If the recaptcha option is on then contact page will appear with a captcha otherwise without a captcha. By default it is off.", 'butterbelly'),
            "id" => "inkthemes_recaptcha_option",
            "std" => "off",
            "type" => "radio",
            "options" => $captcha_option),
//****=============================================================================****//
//****-----------This code is used for creating color styleshteet options----------****//							
//****=============================================================================****//				
        array("name" => __("Styling Options", 'butterbelly'),
            "type" => "heading"),
        array("name" => __("Theme Stylesheet", 'butterbelly'),
            "desc" => __("Select the color of the theme from different available colors.", 'butterbelly'),
            "id" => "inkthemes_altstylesheet",
            "std" => "teal-green",
            "type" => "select",
            "options" => $alt_stylesheets),
        array("name" => __("Theme Language", 'butterbelly'),
            "desc" => __("By default the theme content displays from left to right which you can change to right to left i.e. switching it to RTL.", 'butterbelly'),
            "id" => "inkthemes_lanstylesheet",
            "std" => "Default",
            "type" => "select",
            "options" => $lan_stylesheets),
        array("name" => __("Custom CSS", 'butterbelly'),
            "desc" => __("Quickly add your custom CSS code to your theme by writing the code in this block.", 'butterbelly'),
            "id" => "inkthemes_customcss",
            "std" => "",
            "type" => "textarea"),
//****=============================================================================****//
//****-------------This code is used for creating social logos options-------------****//					
//****=============================================================================****//
        array("name" => __("Social Icons", 'butterbelly'),
            "type" => "heading"),
        array("name" => __("Twitter URL", 'butterbelly'),
            "desc" => __("Mention the URL of your Twitter here.", 'butterbelly'),
            "id" => "inkthemes_twitter",
            "std" => "",
            "type" => "text"),
        array("name" => __("Facebook URL", 'butterbelly'),
            "desc" => __("Mention the URL of your Facebook here.", 'butterbelly'),
            "id" => "inkthemes_facebook",
            "std" => "",
            "type" => "text"),
        array("name" => __("Rss Feed URL", 'butterbelly'),
            "desc" => __("Mention the URL of your Rss Feed here.", 'butterbelly'),
            "id" => "inkthemes_rss",
            "std" => "",
            "type" => "text"),
        array("name" => __("Google+ URL", 'butterbelly'),
            "desc" => __("Mention the URL of your Google+ here.", 'butterbelly'),
            "id" => "inkthemes_google",
            "std" => "",
            "type" => "text"),
        array("name" => __("Pinterest URL", 'butterbelly'),
            "desc" => __("Mention the URL of your Pinterest here.", 'butterbelly'),
            "id" => "inkthemes_pinterest",
            "std" => "",
            "type" => "text"),
//****=============================================================================****//
//****-------------This code is used for creating Bottom Footer Setting options-------------****//					
//****=============================================================================****//			
        array("name" => __("Footer Settings", 'butterbelly'),
            "type" => "heading"),
        array("name" => __("Footer Contact Details", 'butterbelly'),
            "desc" => __("Mention the contact details here which will be displayed on the top right corner of Footer Section.", 'butterbelly'),
            "id" => "inkthemes_topright",
            "std" => "",
            "type" => "textarea"),
        array("name" => __("Footer Text", 'butterbelly'),
            "desc" => __("Write the text here that will be displayed on the footer i.e. at the bottom of the Website.", 'butterbelly'),
            "id" => "inkthemes_footertext",
            "std" => "",
            "type" => "textarea"),
        //------------------------------------------------------------------//
//-------------This code is used for creating SEO description-------//							
//------------------------------------------------------------------//						
        array("name" => __("SEO Options", 'butterbelly'),
            "type" => "heading"),
        array("name" => __("Meta Keywords (comma separated)", 'butterbelly'),
            "desc" => __("Meta keywords provide search engines with additional information about topics that appear on your site. This only applies to your home page. Keyword Limit Maximum 8", 'butterbelly'),
            "id" => "inkthemes_keyword",
            "std" => "",
            "type" => "textarea"),
        array("name" => __("Meta Description", 'butterbelly'),
            "desc" => __("You should use meta descriptions to provide search engines with additional information about topics that appear on your site. This only applies to your home page.Optimal Length for Search Engines, Roughly 155 Characters", 'butterbelly'),
            "id" => "inkthemes_description",
            "std" => "",
            "type" => "textarea"),
        array("name" => __("Meta Author Name", 'butterbelly'),
            "desc" => __("You should write the full name of the author here. This only applies to your home page.", 'butterbelly'),
            "id" => "inkthemes_author",
            "std" => "",
            "type" => "textarea"));
    return $options;
}
